[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "core-hids"
version = "0.1"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}